name: Node.js CI

on:
  pull_request:
    branches: [ main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: |
       npm install -g sonar-scanner
       sonar-scanner \
        -Dsonar.projectKey=J-hu960_autoversion-node\
        -Dsonar.organization="Jordi Salazar badia" \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.qualitygate.wait=true  # Esto garantiza que la pipeline falle si no pasa el Quality Gate
    env:
      SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Asegúrate de que el token esté configurado correctamente