name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  test_and_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      - run: npm test

      - run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATIONKEY }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true  # Esto garantiza que la pipeline falle si no pasa el Quality Gate
        env:
          SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}

